### ISSUE TITLE
TikTok analytics?

### ISSUE THREAD

**Issue by Aariq** [uace-azmet/azmet-data-preview-and-download#10]
Just curious, why the TikTok tracking?

https://github.com/uace-azmet/azmet-data-preview-and-download/blob/6cc4cd9f17501dec99acf40f8533102731b1e203/app/app.R#L54

**Comment by jeremylweiss** [comment]
Both tiktok and snapchat analytics/scripts are baked into the UA quickstart html that we started with when rebuilding the AZMet website. Haven't yet heard why, particularly with the former.

**Comment by jeremylweiss** [comment]
There actually are five such lines of code to comment out / remove. Done!
