### ISSUE TITLE
Include HTML in head

### ISSUE THREAD

**Issue by Aariq** [uace-azmet/azmet-data-preview-and-download#9]
Currently, if you look at the source of the Shiny app website (e.g. View > Developer > View Source in Chrome), you'll see that this HTML isn't _actually_ incorporated into \<head\>\</head\>
https://github.com/uace-azmet/azmet-data-preview-and-download/blob/6cc4cd9f17501dec99acf40f8533102731b1e203/app/app.R#L40-L44

I'd recommend saving this (minus the \<head\> tag) as a .html file and including it in app.R with something like:

``` r
tags$head(includeHTML("my_custom_head.html"))
```

**Comment by Aariq** [comment]
Similarly, the `<body>` part isn't actually getting included where you'd expect.  The source looks like this, where there is a `<body>` nested inside of `<body>`.  I don't know if this is actually a problem I guess?

```html
<body>
  <div class="container-fluid">
    
      <body class="exclude-node-title layout-no-sidebars page-node-44 path-node node--type-az-flexible-page">
        <a href="[#content](http://127.0.0.1:5708/#content)" class="visually-hidden focusable skip-link">Skip to main content</a>
        <noscript aria-hidden="true"><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-ML2BZB" height="0" width="0" style="display:none;visibility:hidden"></iframe>
        </noscript>
        
        ...
```

**Comment by jeremylweiss** [comment]
These are great points/questions and a much better way to organize the webpage and split code into different files! I'm working on this approach with https://github.com/uace-azmet/azmet-web-app-framing. Once I get it dialed in there, I'll adapt it to the other AZMet web apps with Shiny.

**Comment by jeremylweiss** [comment]
Plus, I'm updating the UA quickstart html, which eliminated the tiktok and snapchat analytics all together. So, we'll have a better solution to that issue.

**Comment by jeremylweiss** [comment]
Updated organization of UA html now in place. The multiple `<body>` code chunks still appear in (View > Developer > View Source in Chrome), but do not appear in (right click > inspect in Chrome)

**Comment by jeremylweiss** [comment]
I'm now working on the multiple `<body>` issue, which is an issue in proper webpages. I also noted two `<html>` sections, as I'm trying to add document-level attributes. This might work for the latter: https://davidruvolo51.github.io/shinytutorials/tutorials/setting-html-attributes/

**Comment by jeremylweiss** [comment]
Funny, I've been reading bits of that book over the past few days in trying to figure out the Shiny-HTML-CSS wiring. We'll have to compare notes!

**Comment by jeremylweiss** [comment]
I think I have the broader issue figured out. Instead of starting with a Shiny app and trying to build the webpage HTML around it, I started with the HTML template of the webpage and plugged the Shiny app into that. 

I currently have it in place [here](https://github.com/uace-azmet/azmet-shiny-template), and am working on updating the `data-preview-and-download` app

Inspiration was from this [posit blog post](https://shiny.posit.co/r/articles/build/templates/).

**Comment by Aariq** [comment]
I didn't know about using templates for Shiny! This approach sounds more in line with what you're trying to do

**Comment by jeremylweiss** [comment]
Me neither, until https://shiny.posit.co/r/articles/build/templates/! Thanks for pushing me on finding a better HTML solution for the AZMet Shiny apps!
